import os


DEFAULT_API_BASE_URL = os.getenv("EXAMSHIELD_API_BASE_URL", "http://127.0.0.1:8000")
AUTOSAVE_INTERVAL_MS = 25_000
MONITORING_HEARTBEAT_INTERVAL_MS = 12_000
FOCUS_LOST_VIOLATION_COOLDOWN_SECONDS = 5.0
DEV_MODE = os.getenv("EXAMSHIELD_DEV_MODE", "1").strip().lower() not in {"0", "false", "no", "off"}
