version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: examshield_postgres
    environment:
      POSTGRES_USER: examshield
      POSTGRES_PASSWORD: examshield
      POSTGRES_DB: examshield
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
